### ISSUE TITLE
Run solver in parallel

### ISSUE THREAD

**Issue by karasinski** [petebachant/NACAFoil-OpenFOAM#14]
It would be nice if a user could pass an additional flag to enable a parallel computation.

Would require a bit of additional work. We would have to define a decomposeParDict, which is easy to set up if we use [scotch](http://cfd.direct/openfoam/user-guide/running-applications-parallel/) for n processors. In Allrun we would then need to call

```
decomposePar
mpirun -np n simpleFoam -parallel > log.simpleFoam  #where n is a user specified number of cores
reconstructPar
```

instead of simply

```
simpleFoam | tee log.simpleFoam
```

May also have to update Allclean to remove the extra files this would create.

**Comment by petebachant** [comment]
In my experience, cases can be sped up using ~80,000 cells per processor. With the default  mesh, we have roughly that amount. 

`Allclean` will only need an additional `rm -rf processor*`. 

I did something similar with

```
#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Copy initial conditions
cp -rf 0.org 0

runApplication blockMesh
runApplication snappyHexMesh -overwrite
runApplication topoSet

if [ "$1" = "-parallel" ]
    then
    nProc=$(getNumberOfProcessors)
    runApplication decomposePar
    ls -d processor* | xargs -I {} rm -rf ./{}/0
    ls -d processor* | xargs -I {} cp -r 0.org ./{}/0
    mpirun -np $nProc simpleFoam -parallel | tee log.simpleFoam
    runApplication reconstructPar
    rm -rf processor*
else
    simpleFoam | tee log.simpleFoam
fi
```
