### ISSUE TITLE
Try running with pimpleFoam

### ISSUE THREAD

**Issue by petebachant** [petebachant/NACAFoil-OpenFOAM#4]
There are convergence issues at high angle of attack that may require unsteady simulations?

**Comment by karasinski** [comment]
Could follow a strategy similar to what is outlined [here](https://www.hpc.ntnu.no/display/hpc/OpenFOAM+-+Airfoil+Calculations).

**Comment by petebachant** [comment]
`paramsweep.read_force_coeffs` will need to be changed to read the latest file and compute means rather than take the last value. Might be a good idea to log standard deviation of the coeffs as well.

**Comment by petebachant** [comment]
I started doing some work on this on the `pimpleFoam` branch. So far, it looks like it may be better to run `pimpleFoam` from the start, or maybe run `potentialFoam` first rather than `simpleFoam`.

**Comment by petebachant** [comment]
I think it may be useful to simply switch to `pimpleFoam` altogether. Here's a NACA 0020 at 20 degrees angle of attack solved with `pimpleFoam` only:

![image](https://cloud.githubusercontent.com/assets/4604869/10023434/2a2a6d08-6120-11e5-957c-87580f715282.png)

![image](https://cloud.githubusercontent.com/assets/4604869/10023491/65aea0ec-6120-11e5-87ef-d9ff0ae7f16d.png)
